services:
  # gateway

  # frontend

  # backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped # 멈추지 않도록