services:
  # gateway

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  # backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped # 멈추지 않도록